services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: agenda
    ports:
      - "5434:5432"
    volumes:
      - ./src/config/api_db.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db






# version: '3.8'

# services:
#   web:
#     image: php:apache
#     ports:
#       - "8080:80"
#     volumes:
#       - ./src:/var/www/html
#     environment:
#       - APACHE_LOG_DIR=/var/log/apache2
